// Integration test against an explicitly supplied disposable Neon branch and test account.
import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createClient } from '@neondatabase/neon-js';
import { createSyncEngine, neonTransport } from '../src/cloud/sync.js';
import * as db from '../src/storage/idb.js';
import { ENTITY_TYPES } from '../src/data/structured.js';
if(!process.env.NEON_TEST_API_URL || !process.env.NEON_TEST_ACCOUNTS) throw new Error('Explicit disposable branch URL and test credentials file required');
const [account]=JSON.parse(await readFile(process.env.NEON_TEST_ACCOUNTS,'utf8'));
const client=createClient({dataApi:{url:process.env.NEON_TEST_API_URL,getToken:async()=>account.jwt}});
const real=neonTransport(client,account.id);let offline=true;
const transport={push:batch=>{if(offline)throw new Error('Simulated offline');return real.push(batch);},pull:cursor=>real.pull(cursor)};
globalThis.GARGOTTEX_CONFIG={neonUrl:'test'};
await db.initDatabase({});
const id=`integration-${Date.now()}`;
await db.putOne('dungeons',{id,name:'Neon offline test',lore:'Champ long conservé',extra:{nested:[1,2,3]}});
await db.putOne('creatures',{id:id+'-creature',dungeon_id:id,name:'À supprimer'});
await db.deleteOne('creatures',id+'-creature');
const engine=createSyncEngine({userId:account.id,transport,onStatus:console.log});
assert.ok((await engine.run()).error);
assert.equal((await db.getAll('sync_outbox')).length,3);
offline=false;
assert.equal(await engine.run(),undefined);
assert.equal((await db.getAll('sync_outbox')).length,0);
const {data,error}=await client.from('dungeons').select('*').eq('id',id).single();
assert.equal(error,null);assert.deepEqual(data.data.extra,{nested:[1,2,3]});
const before=await client.from('entity_revisions').select('revision_id').eq('entity_id',id);
assert.equal(before.error,null);
await real.push([{entity:'dungeons',id,payload:data.data,operation:'upsert'}]);
const after=await client.from('entity_revisions').select('revision_id').eq('entity_id',id);
assert.equal(after.error,null);assert.equal(after.data.length,before.data.length);
console.log('PASS: repeated upsert creates no phantom revision');
for(const type of ENTITY_TYPES) await db.transaction([type],'readwrite',async stores=>stores[type].clear());
await db.clearStore('sync_meta');
assert.equal(await engine.run(),undefined);
assert.equal((await db.getById('dungeons',id)).lore,'Champ long conservé');
assert.equal(await db.getById('creatures',id+'-creature'),undefined);
console.log('PASS: real Neon SDK push/pull, offline recovery, fresh-install reconstruction, tombstones, original fields');
